# Generated by Django 2.0.2 on 2018-03-02 09:06

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=128)),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
                ('street', models.CharField(max_length=128)),
                ('locality', models.CharField(max_length=64)),
                ('postal_code', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=64)),
            ],
        ),
    ]
